### ISSUE TITLE
FYI: Several settings in options.lua are already the defaults

### ISSUE THREAD

**Issue by l-bowman** [bushblade/nvim#13]
I purged these from my fork, but maybe that's just personal preference. I can't recall exactly which ones are redundant. I prefer to keep this file as concise as possible. Check out: https://neovim.io/doc/user/vim_diff.html if you are interested. Thanks for the recent commits!

**Comment by bushblade** [comment]
Thanks, yeah I have them there so I don't forget and can see the possible options easily.
They don't need to be there but it doesn't really add any overhead.
Much of it is from when I first migrated from vimscript and COC.

**Comment by l-bowman** [comment]
Makes sense. Thanks.
