### ISSUE TITLE
CheckHealth issues

### ISSUE THREAD

**Issue by l-bowman** [bushblade/nvim#14]
Couple CheckHealth warnings I found. 

- One can be resolved by installing fd:  https://github.com/sharkdp/fd#installation I added a README mention in the fork.
- Conflicting keymaps detected by whichkey. Have not resolved in my fork yet. Not sure if these are a big deal or not.

**Comment by bushblade** [comment]
Hi @l-bowman 
I do have fd installed, that would be up to you to install it on your system.
Yeah it's not mentioned in the README though.
You can see what I have/use/recommend here in my [dotfiles](https://github.com/bushblade/dotfiles)
IIRC fd and ripgrep are recommended to have installed by Telescope.

**Comment by l-bowman** [comment]
Okay, thank you.
