### ISSUE TITLE
prefer that editor use project-specific prettier version

### ISSUE THREAD

**Issue by l-bowman** [bushblade/nvim#15]
I'm having problems with Prettier in Neovim following an update to the dev dependencies in a project. I am not having this issue in Code. I suspect that Neovim is not using the project-specific version. Also, I am using yarn, not npm.

**Comment by bushblade** [comment]
Hi @l-bowman 
Neovim will use the global installed prettier, so prettier needs to be available on your system $PATH.
So it doesn't need to be installed in the project, all you need is a .prettierrc or .prettierrc.json in your project root, do you have that?

**Comment by bushblade** [comment]
Just pushed a commit that may help you here, but let me know.

**Comment by l-bowman** [comment]
Thanks! In my case, I did perform a global install because it was easier than creating a project-specific config for now. I'll look into that though.

**Comment by bushblade** [comment]
You can have project specific configs, just Nvim will use the globally installed prettier package but it will use your local config.
Prettier is the executable package that formats your code, and a .prettierrc or .prettierrc.json would be your config file in your project.
