### ISSUE TITLE
Trouble getting Volar language server working

### ISSUE THREAD

**Issue by l-bowman** [bushblade/nvim#16]
Any ideas? Thanks! Here is the Volar readout from LspInfo for Vue filetype: 
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/100594833/206278543-025b0aec-ee91-4f93-a58f-3bd4ef38c727.png">

**Comment by bushblade** [comment]
Hi Luke, hope you're well?
My first thought was _what on earth is Volar?_
Looks like you need to install the Vue Language server
```
npm i -g vls
```
That should then work for you in Vue projects.

**Comment by l-bowman** [comment]
Ah, thanks, Will! I'm good. How are you? I did try this npm command. Still getting an error unfortunately:
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/100594833/206284595-a8eeb67d-8f36-477a-b06c-84c35f09eceb.png">

**Comment by bushblade** [comment]
Yeah ok thanks.
Are you sure it's installed?
What is the output of
 ```
which vls
```
or check if it's in your global npm packages
```
npm list -g --depth=0
```

**Comment by l-bowman** [comment]
> ```
> which vls
> ```

/Users/lukebowman/.nvm/versions/node/v14.19.0/bin/vls

<img width="441" alt="image" src="https://user-images.githubusercontent.com/100594833/206285683-39ad7b1e-acc3-419d-8e2a-96bb020f4cd5.png">

**Comment by bushblade** [comment]
Ok so that does look like it's installed.
What happens if your run the language server on it's own in a terminal?
Just run `vls`

**Comment by l-bowman** [comment]
Hmm, just looks like it opens a prompt. Is that expected? Not sure. 
<img width="174" alt="image" src="https://user-images.githubusercontent.com/100594833/206286554-c912ba0f-be69-46e9-92b9-afa185fbdcae.png">

**Comment by bushblade** [comment]
Ah for some reason your command to start the server is incorrect.
It should be  `vls` and for you nvim lsp is running `vue-language-server`
Have you set custom config for your vue lsp?
![Screenshot_2022-12-07_20-18-57](https://user-images.githubusercontent.com/21976188/206286969-80d5611d-5a70-4f45-8a99-3667ab25e826.png)

**Comment by l-bowman** [comment]
Ah, interesting. Here is my vue.lua: 
<img width="719" alt="image" src="https://user-images.githubusercontent.com/100594833/206287174-fa1b337d-bab2-4de6-ba01-b19ecc1f5c78.png">

**Comment by bushblade** [comment]
Yeah just checked your repo and I see that.

**Comment by l-bowman** [comment]
I updated it to be "volar". That's the only change.

**Comment by bushblade** [comment]
Ah ok, didn't spot that. Yeah change it back to use the vue language server.
`require("lspconfig").vuels.setup({})
`

**Comment by bushblade** [comment]
Or I guess raise an issue with [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) as they must be using the wrong command to run the server by default.

**Comment by l-bowman** [comment]
> require("lspconfig").vuels.setup({})

I changed it back, but I believe this is leveraging Vetur, not Volar. I'm seeing errors in my editor that Volar should not flag.

**Comment by bushblade** [comment]
If I'm honest I've not written any Vue in a long time so wasn't even aware of Volar.
I just fired up a create-vite Vue and TS project and it seems to be working as expected using TS language server and VLS for me.

**Comment by l-bowman** [comment]
No problem. I'm very confused why this is not working. Some path problem maybe? I don't know.

**Comment by l-bowman** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/100594833/206290204-c8056398-b3a4-4d0d-971e-4df64d4e5523.png">
Don't know if this means anything to you.

**Comment by bushblade** [comment]
Yeah looks like you need to pass a flag to the language server.
So if you're testing running it then try
`vue-language-server --stdio`

**Comment by bushblade** [comment]
I'm curious as to your reasons for using Volar instead of Vuels.
I don't really know the differences but Vuels seems to have more active development and is what the Vetur VS code extension uses I believe.

**Comment by bushblade** [comment]
Ah Volar has better support for script setup apparently, so you don't get warnings like _... is declared but never read_
and _... has no default export_

**Comment by bushblade** [comment]
Ok so I just tried using Volar instead of VueLs and it seems to work ok for me...
Better than VueLS for TS and Vue projects it would seem...

![Screenshot_2022-12-07_21-02-48](https://user-images.githubusercontent.com/21976188/206295318-e1572164-9a16-4fe2-a6c4-9bd98b0d8e02.png)


So for you it just seems to be an issue with your global install?

**Comment by l-bowman** [comment]
Yeah, it's super frustrating. I don't know why. Any tips for diagnosing this?

**Comment by bushblade** [comment]
Did the language server run on it's own with...
`vue-language-server --stdio` ?

**Comment by l-bowman** [comment]
> Did the language server run on it's own with... `vue-language-server --stdio` ?

Yeah, that seems to work.

**Comment by l-bowman** [comment]
Actually, not sure. Maybe not.

**Comment by l-bowman** [comment]
<img width="338" alt="image" src="https://user-images.githubusercontent.com/100594833/206296406-a9191737-efc6-4f1d-8468-7851e2c6e1bb.png">

**Comment by bushblade** [comment]
Yeah that looks correct, you don't get any output, but it is doing something.
Maybe check your lsp logs then?
For me it's in `~.local/state/nvim/lsp.log`
`:LspInfo` should tell you where your logs are stored.
Or run `:LspLog` though it's easier to search through the file if you open it directly.

**Comment by l-bowman** [comment]
Bizarrely, it is now finding an executable after reinstalling for the 5th time, but I am getting a new error.
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/100594833/206297973-2942ddc6-db35-404a-a301-4a702249a9a1.png">
 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/100594833/206297818-f554a842-1d66-4dd8-905c-fc1bffabf8b9.png">

**Comment by l-bowman** [comment]
Here is my vue.lua currently: 
<img width="950" alt="image" src="https://user-images.githubusercontent.com/100594833/206298368-10b1a940-d6ab-448f-86c3-66332dc3655c.png">

**Comment by bushblade** [comment]
Anything useful in the logs?
Yeah that does seem to be the example setting but not sure why you would want it running in React file types or json for that matter.

**Comment by l-bowman** [comment]
Yeah, I can probably remove react at least. I borrowed the filetype config from a forum post. Here is the end of the logs: 
<img width="1454" alt="image" src="https://user-images.githubusercontent.com/100594833/206299365-a0591464-3700-4603-a1a6-cbb6e87406db.png">

**Comment by bushblade** [comment]
Hhm nothing it would seem for vue-language-server that I can see.
If you open the file instead of viewing output you can search in the file for vue?
Are you using a nightly build of Neovim? Or latest stable release?

**Comment by l-bowman** [comment]
Nightly build.

**Comment by l-bowman** [comment]
Ah, here is an error for Vue recently: 
<img width="1450" alt="image" src="https://user-images.githubusercontent.com/100594833/206300479-61cccb49-cda5-4fc8-99df-9aa3a47bc759.png">

**Comment by bushblade** [comment]
Ah ok, I'm on 0.8.1
The log output looks to point to an issue in your project.
Can you try starting a fresh new Vue app with Vite and TS and see if it works there? Then you know it's something in your project.
```
npx create-vite
```
Choose Vue and TS and open that project up.

**Comment by l-bowman** [comment]
Okay, maybe that's it. Hmm, thanks for your help. This one might be a little convoluted to figure out. I think there are no problems with the project in VS Code and Volar setup in takeover mode.

**Comment by l-bowman** [comment]
I didn't get the same error with the new create-vite project, so it may indeed be the specific project.

**Comment by l-bowman** [comment]
Going back to vuels until I can get this sorted out. Thanks again.

**Comment by l-bowman** [comment]
Found possibly the same issue: https://github.com/neovim/neovim/issues/20010

**Comment by l-bowman** [comment]
I found the issue. Per the guidance in the link above, I had to set my tsdk path manually.

**Comment by l-bowman** [comment]
Also, thanks a ton for the help and moral support!

**Comment by bushblade** [comment]
Ah nice one. Yes we had to do that also to get astro language server working correctly.
No problem, glad you got a solution.
