### ISSUE TITLE
Improve undo functionality

### ISSUE THREAD

**Issue by ghost** [bushblade/nvim#2]
Turning on persistent redo is incredibly useful. This can be accomplished in VimScript as follows:
```
try
    set undodir=~/.vim_runtime/temp_dirs/undodir
    set undofile
catch
endtry
```
Additionally, the following plugin really takes advantage of Vim's tree storage of undos. The usefulness is quickly apparent when you need it: https://github.com/mbbill/undotree

Thanks! Keep up the awesome work!

**Comment by bushblade** [comment]
To be honest this is the first I have heard of persistent undo-redo.
Is this something you have used frequently then?
Any thoughts on this @ShivamJoker ?

**Comment by ShivamJoker** [comment]
Wow this would be cool, I didn't know about it either.

It'll be helpful to have a track in vim as well instead of just git.

**Comment by ghost** [comment]
I use this plugin all the time, and it makes life way better. I think you will like this feature a lot. I suggest using something like `leader-u` to open Undotree.

**Comment by ghost** [comment]
Opened a PR.
