### ISSUE TITLE
Rust is not well supported

### ISSUE THREAD

**Issue by ghost** [bushblade/nvim#3]
Code-highlighting, intellisense, completion, and formatting are not working for Rust. It would be great to have this working. Thanks.

**Comment by bushblade** [comment]
Hi @grognaak 
Highlighting in Rust should work as long as the treesitter parser is installed.
You can check if you have the parser installed by checking `:TSInstallInfo`
Do you see a check next to Rust?
![Screenshot_2022-05-23_20-26-16](https://user-images.githubusercontent.com/21976188/169891988-ce0dbacb-6fc8-4bc3-b9ca-30eec8c201c9.png)
As for completion then that comes from the language server, which is configured, so perhaps you don't have the language server installed?
When you have a rust file open run `:LspInfo` What do you see as the output?
You should have something like...
![Screenshot_2022-05-23_20-30-03](https://user-images.githubusercontent.com/21976188/169892503-cb4dd59c-2229-442a-8449-ed5092b36690.png)
I'm using [rust-analyzer](https://github.com/rust-lang/rust-analyzer), and that is what the config is set to use, do you have that installed?
The language server does provide formatting so you can format a file by shortcut `<leader> l f `
But yeah it should work, so let me know how you go.

**Comment by ghost** [comment]
This appears to be working now, and I don't have a good explanation for why it wasn't before. I do indeed have the prerequisites. Apologies!
