### ISSUE TITLE
Trim whitespace on save

### ISSUE THREAD

**Issue by ghost** [bushblade/nvim#5]
For most files, this would be a useful feature.

**Comment by bushblade** [comment]
Hi @grognaak.
In most cases your formatter will do this.
What file types specifically and formatter are you using?
Currently in the config trailing whitespace will be highlighted so obvious if you have any.
You can also run a substitution `:%s/\s\+$//e` to remove all trailing whitespace in your file.
You could bind that to some shortcut if you really need, personally this hasn't been an issue for me as I usually use a formatter.
Let me know what you think.

**Comment by ghost** [comment]
I noticed this issue with JSON files, but it's really not a problem for most file types. Probably not worth worrying about. I appreciate that substitution example. Thank you!

**Comment by bushblade** [comment]
It _should_ format on write in json files, however it doesn't always and I have never pinned down the reason as to why.
You can manually run `:FormatWrite`  and that will run pretter and save.
