### ISSUE TITLE
System clipboard question

### ISSUE THREAD

**Issue by ghost** [bushblade/nvim#6]
Just a general question. What strategy do you use to avoid overwriting your copies with deletions? I find that I do this many times each day with this setting. I know that I could delete to the blackhole buffer, but I find it difficult to remember to do this and less friendly than simply copying to the register I want to use when the system clipboard use is set to false.

**Comment by bushblade** [comment]
Hi again @grognaak 
To be honest most of the time I just use my clipboard manager.
I'm on Manjaro XFCE and have Clipman installed by default.
So the complete delete and yank history is in there.
However deleting will go to the numbered registers, so 1 will be the latest, 2 the previous and so on.
Yanking will go to the + register.
You can see your registers by hitting `"` from normal mode, then paste from a register if you want with `"<register>p`
Hope that helps.

**Comment by ghost** [comment]
Cool, thanks. I'm at odds over whether I prefer this setting over the default, but I'll keep trying it this week.
